/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_go_gl_model_Ms3dModel */

#ifndef _Included_com_graphics_engine_model_Ms3dModel
#define _Included_com_graphics_engine_model_Ms3dModel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_graphics_engine_model_Ms3dModel_DBG
#define com_graphics_engine_model_Ms3dModel_DBG 1L
/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    loadModel
 * Signature: (IJJ)I
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_model_Ms3dModel_loadModel
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    loadAnimation
 * Signature: (IIJJ)I
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_model_Ms3dModel_loadAnimation
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    getErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_graphics_engine_model_Ms3dModel_getErrorMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    releaseModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_model_Ms3dModel_releaseModel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    releaseAnimation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_model_Ms3dModel_releaseAnimation
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    getGroupCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_model_Ms3dModel_getGroupCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    getTextureNames
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_graphics_engine_model_Ms3dModel_getTextureNames
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    getGroupTextureIndex
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_model_Ms3dModel_getGroupTextureIndex
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    renderGroup
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_model_Ms3dModel_renderGroup
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    playAnimation
 * Signature: (IIZF)I
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_model_Ms3dModel_playAnimation
  (JNIEnv *, jclass, jint, jint, jboolean, jfloat);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    onAnimationRepeat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_model_Ms3dModel_onAnimationRepeat
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    onAnimationEnd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_model_Ms3dModel_onAnimationEnd
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    onAnimationUpdate
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_model_Ms3dModel_onAnimationUpdate
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    fixAnimationTranslation
 * Signature: (IIIFFF)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_model_Ms3dModel_fixAnimationTranslation
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_graphics_engine_model_Ms3dModel
 * Method:    fixAnimationRotation
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_model_Ms3dModel_fixAnimationRotation
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
