/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_graphics_engine_util_NdkUtil */

#ifndef _Included_com_graphics_engine_util_NdkUtil
#define _Included_com_graphics_engine_util_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    detectGLES20
 * Signature: (Landroid/content/Context;)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_detectGLES20
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
