/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_go_gl_util_NdkUtil */

#ifndef _Included_com_graphics_engine_util_NdkUtil
#define _Included_com_graphics_engine_util_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_graphics_engine_util_NdkUtil_SAVE_RESOURCE_TO_NDK
#define com_graphics_engine_util_NdkUtil_SAVE_RESOURCE_TO_NDK 0L
#undef com_graphics_engine_util_NdkUtil_SAVE_ICON_TO_NDK
#define com_graphics_engine_util_NdkUtil_SAVE_ICON_TO_NDK 1L
/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_init
  (JNIEnv *, jclass);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    glVertexAttribPointer
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_glVertexAttribPointer
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    glDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_glDrawElements
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    saveScreenshotTGA
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_saveScreenshotTGA
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    saveScreenshot
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_saveScreenshot
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    saveScreenshotBitmap
 * Signature: (IIIILandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_saveScreenshotBitmap
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    convertToHSVInternal
 * Signature: (Landroid/graphics/Bitmap;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_graphics_engine_util_NdkUtil_convertToHSVInternal
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    detectGLES20
 * Signature: (Landroid/content/Context;)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_detectGLES20
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    getLibVersionInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_util_NdkUtil_getLibVersionInternal
  (JNIEnv *, jclass);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    saveBitmapInternal
 * Signature: (Landroid/graphics/Bitmap;)I
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_util_NdkUtil_saveBitmapInternal
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    releasePixelsInternal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_releasePixelsInternal
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    restorePixelsInternal
 * Signature: (Landroid/graphics/Bitmap;I)I
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_util_NdkUtil_restorePixelsInternal
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    glTexImage2D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_glTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    glTexSubImage2D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_graphics_engine_util_NdkUtil_glTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_graphics_engine_util_NdkUtil
 * Method:    getPixel
 * Signature: 获取像素数据
 */
JNIEXPORT jint JNICALL Java_com_graphics_engine_util_NdkUtil_getPixelInternal(
		JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
